### ISSUE TITLE
sort the tests by their source file's modification time

### ISSUE THREAD

**Issue by disruptek** [status-im/nim-testutils#5]
...to run the most-recently-modified tests first.

**Comment by disruptek** [comment]
Closed in #8.

**Comment by arnetheduck** [comment]
this makes the output not match the previous run which is a pain if you're comparing test runs, no?

**Comment by kdeme** [comment]
I also don't really understand the point of this feature. But I understand it is only activated with the sort option?

**Comment by kdeme** [comment]
Oh, documentation says it is default `according to the modification time of the test program source`. That is not really what we want, no? Also, how does that even work with git?

**Comment by zah** [comment]
@disruptek shared the motivation with me in a private chat. The idea is that you are  usually iterating on the test files and the most recently modified files are probably the ones you are trying to fix right now. So, the tester helps by running them first and breaking on the first failure.

**Comment by kdeme** [comment]
OK, but i think this shouldn't be default. For CI and comparing you would want to have deterministic results (also in the output) as much as possible.

Also, when trying to fix a test case you could just use `--include` no? Similar as unit tests allows you to do `test "blabla"` at the end.

**Comment by arnetheduck** [comment]
yeah, that's usually what people think they'll achieve - but in fact, you want something else from an incremental test: you want all affected tests to be run, as discovered by dependency analysis. running the tests in modification order feels like an anti-feature: you don't get the deterministic order you need for comparing runs, you don't get a completely random order that you need to discover bad tests (ie those that depend on execution order) and you get only a mild advantage - the latest modified test is only sometimes the one that is the most interesting for a particular run.

I would not want this order when I run tests, and certainly not by default.

**Comment by disruptek** [comment]
- I can do dependency analysis (order discovery) in n^2 runs, if that's what you want.
- if you're comparing test output and not test result status, you're doing it wrong.
- random order is provided as a sort option as well.
- if you know which test is more interesting, you can `touch` it and it will run first.

**Comment by arnetheduck** [comment]
> I can do dependency analysis (order discovery) in n^2 runs, if that's what you want.

by this I mean that the tests that are affected by a code change should be rerun - imagine how a package manager (ie cargo or cmake) will rebuild downstream deps when a core library changes  - this should be per module, so for example `varint` uses `bitops` - if I make a change in the bitops module, the tests for both bitops and varint should run, but not others. It's not an ordering thing - it's a minimal incremental rerun thing.

**Comment by disruptek** [comment]
Dependency analysis without regard to order is much easier, of course.  What do you want to pay?

**Comment by arnetheduck** [comment]
well, the dep analysis would discover what needs rebuilding and .. whatever (alphabetic, last modified etc) .. would sort in which order that gets built. maybe too tricky but ideally you want it down at function and individual test granularity - I guess imports is a start.
